version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=MiPassword123!
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    networks:
      - my-network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: .  # usa tu Dockerfile para construir la imagen
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - SERVER_URL=http://localhost:8080
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://sqlserver:1433;databaseName=AltavistaDB;encrypt=false;trustServerCertificate=true
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=MiPassword123!
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.microsoft.sqlserver.jdbc.SQLServerDriver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - sqlserver
    networks:
      - my-network
    command: >
      sh -c "
        echo 'Esperando SQL Server...';
        until nc -z sqlserver 1433; do
          echo 'SQL Server no listo, esperando 5s...';
          sleep 5;
        done;
        echo 'SQL Server listo, iniciando backend...';
        sleep 10;
        java -jar /app/app.jar
      "

networks:
  my-network:
    driver: bridge